spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat_order?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8883
  servlet:
    context-path: /sell
logging:
  config: classpath:logback-spring.xml
  level:
    com.devil.sell.po.mapper: trace
wx:
#  appId: wxd898fcb01713c658
  appId: wx38ab4f5fb66a4395
  appSecret: bd954f582014af7fbd70baf7555fa438
#  appId: wx125347343576487c
#  appSecret: 2122420d97c6f5849d563e5dc4f55a5b

  openAppId: wx38ab4f5fb66a4395
  openAppSecret: bd954f582014af7fbd70baf7555fa438
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: /usr/local/doc/h5.p12
  notifyUrl: http://47.94.150.75/sell/pay/notify
  templateId:
    orderStatus: iqHAuaycv9zyjc2g1RPFJrtXVYPIWfRukVLiNBtwf-Q

projectUrl:
  wechatMpAuthorize: /sell/wechat/userInfo
  wechatOpenAuthorize: /sell/wechat/qrUserInfo
  sell: http://47.94.150.75/
mybatis:
  mapper-locations: classpath:mapper/*.xml
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: D:/
#  level: debug
