spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat_order?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  shardingsphere:
    datasource:
      names: db1,db2
      db1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/wechat_order
        username: root
        password: 123456
      db2:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/wechat_order1
        username: root
        password: 123456

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8883
  servlet:
    context-path: /sell
logging:
  config: classpath:logback-spring.xml
  level:
    com.devil.sell.po.mapper: trace
wx:
#  公众号测试号：
#  appId: wx38ab4f5fb66a4395
  appSecret: bd954f582014af7fbd70baf7555fa438
#服务号/公众平台 -- 微信授权
#  appId: wx125347343576487c
#  appSecret: 2122420d97c6f5849d563e5dc4f55a5b
#开放平台 -- 扫码登录
  openAppId: wx38ab4f5fb66a4395
  openAppSecret: bd954f582014af7fbd70baf7555fa438
#支付平台
  appId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
#发起支付不需要证书/退款需要
  keyPath: D:\Wechat Order\coding-117\doc\h5.p12
  notifyUrl: http://hyj.nat300.top/sell/pay/notify
  templateId:
    orderStatus: iqHAuaycv9zyjc2g1RPFJrtXVYPIWfRukVLiNBtwf-Q

project-url:
  wechatMpAuthorize: /sell/wechat/userInfo
  wechatOpenAuthorize: /sell/wechat/qrUserInfo
  sell: http://hyj.nat300.top
upyun:
  bucketName:
  username:
  password:
  imageHost:
mybatis:
  mapper-locations: classpath:mapper/*.xml
sharding:
  jdbc:
    config:
      sharding:
        tables: postion
        default-database-strategy:
          inline:
            algorithm-expression:
            sharding-column:


#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: D:/
#  level: debug
